services:
    verdaccio:
        image: verdaccio/verdaccio
        container_name: verdaccio
        ports:
            - "4873:4873"
        volumes:
            - ./.verdaccio/storage:/verdaccio/storage
            - ./.verdaccio/config:/verdaccio/conf
        restart: always
